// Core type definitions for the AI Interviewer application

export interface Interview {
  id: string;
  jobId?: string;
  title: string;
  company: string;
  position: string;
  interviewType: InterviewType;
  status: InterviewStatus;
  startedAt: string;
  endedAt?: string;
  duration?: number;
  transcript: Message[];
  feedback?: InterviewFeedback;
  createdAt: string;
  updatedAt: string;
}

export interface Job {
  id: string;
  title: string;
  company: string;
  description?: string;
  status: JobStatus;
  appliedAt?: string;
  interviewIds: string[];
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Message {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: string;
  // Audio-related metadata
  audioFile?: string; // Path to recorded audio file
  asrTranscript?: string; // Raw ASR output before any processing
  ttsAudioFile?: string; // Path to generated TTS audio
  agentPersonaId?: string; // Which persona was active
  vadMetadata?: VADMetadata; // Voice activity detection data
  audioDeviceId?: string; // Which device was used
}

export interface VADMetadata {
  speechDetected: boolean;
  confidence: number;
  silenceDuration?: number; // milliseconds
  speechDuration?: number; // milliseconds
  vadEngine: string; // e.g., 'webrtc-vad', 'silero-vad'
}

export interface QuestionFeedback {
  questionIndex: number;
  question: string;
  answer: string;
  score: number;           // 0-100
  rating: 'excellent' | 'good' | 'needs-improvement';
  strengths: string[];
  improvements: string[];
  suggestedAnswer: string;
}

export interface InterviewFeedback {
  overallScore: number;
  questionFeedbacks: QuestionFeedback[];
  strengths: string[];
  weaknesses: string[];
  suggestions: string[];
  detailedFeedback: string;
}

export interface UserSettings {
  userId: string;
  theme: 'light' | 'dark' | 'system';
  language: string;
  notifications: boolean;
  autoSave: boolean;
  defaultInterviewDuration: number;
  createdAt: string;
  updatedAt: string;
}

export interface InterviewerSettings {
  modelProvider: string;
  modelName: string;
  extractionModelName?: string;
  temperature: number;
  maxTokens: number;
  interviewStyle: InterviewStyle;
  questionDifficulty: 'easy' | 'medium' | 'hard';
  numberOfQuestions: number;
  includeFollowUps: boolean;
  provideFeedback: boolean;
  // Voice settings
  voiceMode: boolean; // Enable voice interaction
  asrModel?: string; // ASR model for speech recognition
  ttsVoice?: string; // TTS voice selection
  vadSensitivity: number; // 0-1, sensitivity for voice detection
  autoPlayTTS: boolean; // Automatically play TTS responses
  recordingQuality: 'low' | 'medium' | 'high';
  // Active persona
  activePersonaId?: string;
}

export interface AgentPersona {
  id: string;
  name: string;
  description: string;
  systemPrompt: string;
  interviewStyle: InterviewStyle;
  questionDifficulty: 'easy' | 'medium' | 'hard';
  ttsVoice?: string;
  avatarUrl?: string;
  isDefault: boolean;
  createdAt: string;
  updatedAt: string;
  // v5: Structured interview arc fields (generated by persona generation)
  personaRole?: string;
  q1Topic?: string;
  q2Topic?: string;
  q3Topic?: string;
  q4Topic?: string;
  q5Topic?: string;
  primaryProbeArea?: string;
  mustCoverTopic1?: string;
  mustCoverTopic2?: string;
  mustCoverTopic3?: string;
  validateClaim1?: string;
  validateClaim2?: string;
  watchSignal1?: string;
  watchSignal2?: string;
  // Voice gender for TTS voice matching
  gender?: 'male' | 'female' | 'neutral';
}

export interface AudioDevice {
  deviceId: string;
  label: string;
  kind: 'audioinput' | 'audiooutput';
  groupId?: string;
}

export interface AudioSettings {
  inputDeviceId?: string;
  outputDeviceId?: string;
  inputVolume: number; // 0-100
  outputVolume: number; // 0-100
  echoCancellation: boolean;
  noiseSuppression: boolean;
  autoGainControl: boolean;
  recordingQuality?: 'low' | 'medium' | 'high';
}

/**
 * VAD (Voice Activity Detection) tunable configuration.
 * Controls how aggressively speech start/end is detected.
 */
export interface VADConfig {
  /** Energy level threshold to consider as speech (0-1). Lower = more sensitive. Default: 0.01 */
  energyThreshold: number;
  /** Minimum consecutive speech duration (ms) before triggering speech-start. Default: 250 */
  minSpeechMs: number;
  /** Minimum silence duration (ms) before triggering speech-end. Default: 800 */
  minSilenceMs: number;
  /** Number of consecutive frames above threshold before triggering onset. Default: 2 */
  onsetFrames: number;
  /** Number of extra frames to keep after energy drops below threshold. Default: 6 */
  hangoverFrames: number;
}

/**
 * ASR (Automatic Speech Recognition) audio processing configuration.
 * Controls audio capture parameters and WebSocket behavior.
 */
export interface ASRConfig {
  /** ScriptProcessor buffer size in samples. Default: 4096 */
  bufferSize: number;
  /** Target sample rate in Hz. Must match Whisper expectation. Default: 16000 */
  targetSampleRate: number;
  /** Delay (ms) before closing WebSocket after stop, to allow final transcript to arrive. Default: 3000 */
  wsCloseDelayMs: number;
}

/** Default VAD configuration values */
export const DEFAULT_VAD_CONFIG: VADConfig = {
  energyThreshold: 0.01,
  minSpeechMs: 250,
  minSilenceMs: 800,
  onsetFrames: 2,
  hangoverFrames: 6,
};

/** Default ASR configuration values */
export const DEFAULT_ASR_CONFIG: ASRConfig = {
  bufferSize: 4096,
  targetSampleRate: 16000,
  wsCloseDelayMs: 3000,
};

export interface MCPConfig {
  servers: MCPServer[];
  enabled: boolean;
}

export interface MCPServer {
  id: string;
  name: string;
  command: string;
  args: string[];
  env?: Record<string, string>;
  enabled: boolean;
}

export interface UploadedDocument {
  id: string;
  type: 'resume' | 'job_post';
  fileName: string;
  filePath: string;
  mimeType: string;
  fileSize: number;
  extractedText: string;
  uploadedAt: string;
}

export interface CompatibleModel {
  id: string;
  downloaded: boolean;
  suggested: boolean;
  labels: string[];
  recipe?: string;
  size?: number;
  checkpoint?: string;
}

export interface LemonadeConfig {
  serverURL: string;
  models: ModelConfig[];
  defaultModel: string;
  isConnected: boolean;
}

export interface ModelConfig {
  id: string;
  name: string;
  provider: string;
  maxTokens: number;
  temperature: number;
  isLoaded?: boolean;
}

export type InterviewType = 
  | 'technical'
  | 'behavioral'
  | 'system-design'
  | 'coding'
  | 'general'
  | 'mixed';

export type InterviewStatus = 
  | 'scheduled'
  | 'in-progress'
  | 'completed'
  | 'cancelled';

export type JobStatus = 
  | 'interested'
  | 'applied'
  | 'interviewing'
  | 'offer'
  | 'rejected'
  | 'accepted'
  | 'declined';

export type InterviewStyle = 
  | 'conversational'
  | 'formal'
  | 'challenging'
  | 'supportive';

export interface AppState {
  currentInterview?: Interview;
  interviews: Interview[];
  jobs: Job[];
  settings: UserSettings;
  interviewerSettings: InterviewerSettings;
  isLoading: boolean;
  error?: string;
}

export interface SystemInfo {
  processor: string;
  physicalMemory: string;
  devices: {
    cpu?: {
      cores: number;
      available: boolean;
    };
    amd_igpu?: {
      vram_gb: number;
      available?: boolean;
    };
    nvidia_dgpu?: {
      vram_gb: number;
      available?: boolean;
    };
    npu?: {
      available: boolean;
    };
  };
  recipes?: {
    llamacpp?: {
      backends: {
        vulkan?: { available: boolean };
        rocm?: { available: boolean };
        cuda?: { available: boolean };
        cpu?: { available: boolean };
      };
    };
    whispercpp?: {
      backends: {
        vulkan?: { available: boolean };
        cuda?: { available: boolean };
        cpu?: { available: boolean };
      };
    };
  };
}

export interface LoadedModel {
  model_name: string;
  type: 'llm' | 'audio' | 'embedding' | 'reranking' | 'image';
  device: string; // e.g., "cpu", "gpu", "npu", "gpu npu"
  backend?: string;
}

export interface ServerHealth {
  status: string;
  all_models_loaded: LoadedModel[];
  max_models?: {
    llm?: number;
    audio?: number;
    tts?: number;
    embedding?: number;
    reranking?: number;
    image?: number;
  };
}

export interface IPC {
  // Interview operations
  startInterview: (config: Partial<Interview>, personaId?: string) => Promise<Interview>;
  endInterview: (interviewId: string) => Promise<Interview>;
  sendMessage: (interviewId: string, message: string) => Promise<Message>;
  sendMessageStreaming: (interviewId: string, message: string) => Promise<Message>;
  onLLMToken: (callback: (token: string) => void) => void;
  offLLMToken: () => void;
  onLLMDone: (callback: (response: string) => void) => void;
  offLLMDone: () => void;
  onLLMError: (callback: (error: string) => void) => void;
  offLLMError: () => void;
  getInterview: (interviewId: string) => Promise<Interview>;
  getAllInterviews: () => Promise<Interview[]>;
  deleteInterview: (interviewId: string) => Promise<void>;
  updateInterviewTranscript: (interviewId: string, transcript: Message[]) => Promise<void>;
  
  // Job operations
  createJob: (job: Partial<Job>) => Promise<Job>;
  updateJob: (jobId: string, updates: Partial<Job>) => Promise<Job>;
  getJob: (jobId: string) => Promise<Job>;
  getAllJobs: () => Promise<Job[]>;
  deleteJob: (jobId: string) => Promise<void>;
  
  // Settings operations
  getSettings: () => Promise<UserSettings>;
  updateSettings: (settings: Partial<UserSettings>) => Promise<UserSettings>;
  getInterviewerSettings: () => Promise<InterviewerSettings>;
  updateInterviewerSettings: (settings: Partial<InterviewerSettings>) => Promise<InterviewerSettings>;
  
  // Model operations
  getAvailableModels: () => Promise<ModelConfig[]>;
  testModelConnection: (modelId: string) => Promise<boolean>;
  loadModel: (modelId: string, options?: {
    ctx_size?: number;
    llamacpp_backend?: 'vulkan' | 'rocm' | 'metal' | 'cpu';
    llamacpp_args?: string;
    save_options?: boolean;
  }) => Promise<{ success: boolean; message?: string } | false>;
  unloadModel: (modelId: string) => Promise<{ success: boolean; message?: string } | false>;
  pullModel: (modelId: string) => Promise<{ success: boolean; message?: string } | false>;
  pullModelStreaming: (modelId: string) => Promise<{ success: boolean; message?: string } | false>;
  onPullProgress: (callback: (data: {
    file?: string;
    fileIndex?: number;
    totalFiles?: number;
    bytesDownloaded?: number;
    bytesTotal?: number;
    percent: number;
  }) => void) => void;
  offPullProgress: () => void;
  deleteModel: (modelId: string) => Promise<{ success: boolean; message?: string } | false>;
  listAllModels: () => Promise<CompatibleModel[]>;
  
  // Server operations
  checkServerHealth: () => Promise<boolean>;
  getServerStatus: () => Promise<{ isRunning: boolean; url: string }>;
  getWebSocketPort: () => Promise<number | null>;
  refreshModels: () => Promise<ModelConfig[]>;
  getSystemInfo: () => Promise<SystemInfo | null>;
  getServerHealth: () => Promise<ServerHealth | null>;
  checkLemonadeInstallation: () => Promise<{
    installed: boolean;
    version: string | null;
    binaryPath: string | null;
  }>;
  
  // Persona operations
  createPersona: (personaData: Partial<AgentPersona>) => Promise<AgentPersona>;
  getAllPersonas: () => Promise<AgentPersona[]>;
  getPersonaById: (personaId: string) => Promise<AgentPersona>;
  updatePersona: (personaId: string, updates: Partial<AgentPersona>) => Promise<AgentPersona>;
  deletePersona: (personaId: string) => Promise<boolean>;
  setDefaultPersona: (personaId: string) => Promise<boolean>;
  getDefaultPersona: () => Promise<AgentPersona | null>;
  generatePersona: (input: {
    jobDescriptionText: string;
    resumeText: string;
    interviewType: string;
    company: string;
    position: string;
  }) => Promise<{
    persona: AgentPersona;
    jobAnalysis: string;
    resumeAnalysis: string;
  }>;

  // Audio operations
  saveAudioRecording: (audioData: { interviewId: string; messageId: string; audioBlob: string }) => Promise<{ success: boolean; filepath: string }>;
  getAudioRecordingsPath: () => Promise<string>;
  deleteAudioRecording: (filepath: string) => Promise<{ success: boolean; error?: string }>;

  // Feedback operations
  generateFeedback: (interviewId: string) => Promise<InterviewFeedback>;
  onFeedbackProgress: (callback: (data: { questionIndex: number; totalQuestions: number; status: string }) => void) => void;
  offFeedbackProgress: () => void;

  // Document operations
  uploadDocument: (data: { type: 'resume' | 'job_post'; fileName: string; fileData: string }) => Promise<UploadedDocument>;
  getDocuments: (type?: 'resume' | 'job_post') => Promise<UploadedDocument[]>;
  getDocument: (id: string) => Promise<UploadedDocument | null>;
  getDocumentFileData: (id: string) => Promise<{ base64: string; mimeType: string; fileName: string } | null>;
  deleteDocument: (id: string) => Promise<boolean>;
  extractJobDetails: (jobPostDocId: string) => Promise<{
    title: string;
    company: string;
    position: string;
    interviewType: string;
  }>;

  // MCP operations
  getMCPServers: () => Promise<MCPServer[]>;
  updateMCPServers: (servers: MCPServer[]) => Promise<void>;
}
