// Core type definitions for the AI Interviewer application

export interface Interview {
  id: string;
  jobId?: string;
  title: string;
  company: string;
  position: string;
  interviewType: InterviewType;
  status: InterviewStatus;
  startedAt: string;
  endedAt?: string;
  duration?: number;
  transcript: Message[];
  feedback?: InterviewFeedback;
  createdAt: string;
  updatedAt: string;
}

export interface Job {
  id: string;
  title: string;
  company: string;
  description?: string;
  status: JobStatus;
  appliedAt?: string;
  interviewIds: string[];
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Message {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: string;
  // Audio-related metadata
  audioFile?: string; // Path to recorded audio file
  asrTranscript?: string; // Raw ASR output before any processing
  ttsAudioFile?: string; // Path to generated TTS audio
  agentPersonaId?: string; // Which persona was active
  vadMetadata?: VADMetadata; // Voice activity detection data
  audioDeviceId?: string; // Which device was used
}

export interface VADMetadata {
  speechDetected: boolean;
  confidence: number;
  silenceDuration?: number; // milliseconds
  speechDuration?: number; // milliseconds
  vadEngine: string; // e.g., 'webrtc-vad', 'silero-vad'
}

export interface QuestionFeedback {
  questionIndex: number;
  question: string;
  answer: string;
  score: number;           // 0-100
  rating: 'excellent' | 'good' | 'needs-improvement';
  strengths: string[];
  improvements: string[];
  suggestedAnswer: string;
}

export interface InterviewFeedback {
  overallScore: number;
  questionFeedbacks: QuestionFeedback[];
  strengths: string[];
  weaknesses: string[];
  suggestions: string[];
  detailedFeedback: string;
}

export interface UserSettings {
  userId: string;
  theme: 'light' | 'dark' | 'system';
  language: string;
  notifications: boolean;
  autoSave: boolean;
  defaultInterviewDuration: number;
  createdAt: string;
  updatedAt: string;
}

export interface InterviewerSettings {
  modelProvider: string;
  modelName: string;
  extractionModelName?: string;
  temperature: number;
  maxTokens: number;
  interviewStyle: InterviewStyle;
  questionDifficulty: 'easy' | 'medium' | 'hard';
  numberOfQuestions: number;
  includeFollowUps: boolean;
  provideFeedback: boolean;
  // Voice settings
  voiceMode: boolean; // Enable voice interaction
  asrModel?: string; // ASR model for speech recognition
  ttsVoice?: string; // TTS voice selection
  ttsRate?: number; // TTS speech rate (0.5 - 2.0, default 1.0)
  vadSensitivity: number; // 0-1, sensitivity for voice detection
  autoPlayTTS: boolean; // Automatically play TTS responses
  recordingQuality: 'low' | 'medium' | 'high';
  // Active persona
  activePersonaId?: string;
}

export interface AgentPersona {
  id: string;
  name: string;
  description: string;
  systemPrompt: string;
  interviewStyle: InterviewStyle;
  questionDifficulty: 'easy' | 'medium' | 'hard';
  ttsVoice?: string;
  avatarUrl?: string;
  isDefault: boolean;
  createdAt: string;
  updatedAt: string;
  // v5: Structured interview arc fields (generated by persona generation)
  personaRole?: string;
  // Full persona context for phase-based prompting
  personaFullContext?: string;  // Complete interviewer backstory and approach (2-4 sentences)
  personaExperience?: string;  // Years of experience (e.g., "8 years", "12+ years")
  q1Topic?: string;
  q2Topic?: string;
  q3Topic?: string;
  q4Topic?: string;
  q5Topic?: string;
  primaryProbeArea?: string;
  mustCoverTopic1?: string;
  mustCoverTopic2?: string;
  mustCoverTopic3?: string;
  validateClaim1?: string;
  validateClaim2?: string;
  watchSignal1?: string;
  watchSignal2?: string;
  // Voice gender for TTS voice matching
  gender?: 'male' | 'female' | 'neutral';
}

export interface AudioDevice {
  deviceId: string;
  label: string;
  kind: 'audioinput' | 'audiooutput';
  groupId?: string;
}

export interface AudioSettings {
  inputDeviceId?: string;
  outputDeviceId?: string;
  inputVolume: number; // 0-100
  outputVolume: number; // 0-100
  echoCancellation: boolean;
  noiseSuppression: boolean;
  autoGainControl: boolean;
  recordingQuality?: 'low' | 'medium' | 'high';
}

/**
 * VAD (Voice Activity Detection) tunable configuration.
 * Controls how aggressively speech start/end is detected.
 */
export interface VADConfig {
  /** Energy level threshold to consider as speech (0-1). Lower = more sensitive. Default: 0.01 */
  energyThreshold: number;
  /** Minimum consecutive speech duration (ms) before triggering speech-start. Default: 250 */
  minSpeechMs: number;
  /** Minimum silence duration (ms) before triggering speech-end. Default: 800 */
  minSilenceMs: number;
  /** Number of consecutive frames above threshold before triggering onset. Default: 2 */
  onsetFrames: number;
  /** Number of extra frames to keep after energy drops below threshold. Default: 6 */
  hangoverFrames: number;
}

/**
 * ASR (Automatic Speech Recognition) audio processing configuration.
 * Controls audio capture parameters and WebSocket behavior.
 */
export interface ASRConfig {
  /** ScriptProcessor buffer size in samples. Default: 4096 */
  bufferSize: number;
  /** Target sample rate in Hz. Must match Whisper expectation. Default: 16000 */
  targetSampleRate: number;
  /** Delay (ms) before closing WebSocket after stop, to allow final transcript to arrive. Default: 3000 */
  wsCloseDelayMs: number;
}

/** Default VAD configuration values */
export const DEFAULT_VAD_CONFIG: VADConfig = {
  energyThreshold: 0.01,
  minSpeechMs: 250,
  minSilenceMs: 800,
  onsetFrames: 2,
  hangoverFrames: 6,
};

/** Default ASR configuration values */
export const DEFAULT_ASR_CONFIG: ASRConfig = {
  bufferSize: 4096,
  targetSampleRate: 16000,
  wsCloseDelayMs: 3000,
};

export interface MCPConfig {
  servers: MCPServer[];
  enabled: boolean;
}

export interface MCPServer {
  id: string;
  name: string;
  command: string;
  args: string[];
  env?: Record<string, string>;
  enabled: boolean;
}

export interface UploadedDocument {
  id: string;
  type: 'resume' | 'job_post';
  fileName: string;
  filePath: string;
  mimeType: string;
  fileSize: number;
  extractedText: string;
  uploadedAt: string;
}

export interface CompatibleModel {
  id: string;
  downloaded: boolean;
  suggested: boolean;
  labels: string[];
  recipe?: string;
  size?: number;
  checkpoint?: string;
}

export interface LemonadeConfig {
  serverURL: string;
  models: ModelConfig[];
  defaultModel: string;
  isConnected: boolean;
}

export interface ModelConfig {
  id: string;
  name: string;
  provider: string;
  maxTokens: number;
  temperature: number;
  isLoaded?: boolean;
}

export type InterviewType = 
  | 'technical'
  | 'behavioral'
  | 'system-design'
  | 'coding'
  | 'general'
  | 'mixed';

export type InterviewStatus = 
  | 'scheduled'
  | 'in-progress'
  | 'completed'
  | 'cancelled';

export type JobStatus = 
  | 'interested'
  | 'applied'
  | 'interviewing'
  | 'offer'
  | 'rejected'
  | 'accepted'
  | 'declined';

export type InterviewStyle = 
  | 'conversational'
  | 'formal'
  | 'challenging'
  | 'supportive';

export interface AppState {
  currentInterview?: Interview;
  interviews: Interview[];
  jobs: Job[];
  settings: UserSettings;
  interviewerSettings: InterviewerSettings;
  isLoading: boolean;
  error?: string;
}

export interface SystemInfo {
  processor: string;
  physicalMemory: string;
  devices: {
    cpu?: {
      cores: number;
      available: boolean;
    };
    amd_igpu?: {
      vram_gb: number;
      available?: boolean;
    };
    nvidia_dgpu?: {
      vram_gb: number;
      available?: boolean;
    };
    npu?: {
      available: boolean;
    };
  };
  recipes?: {
    llamacpp?: {
      backends: {
        vulkan?: { available: boolean };
        rocm?: { available: boolean };
        cuda?: { available: boolean };
        cpu?: { available: boolean };
      };
    };
    whispercpp?: {
      backends: {
        vulkan?: { available: boolean };
        cuda?: { available: boolean };
        cpu?: { available: boolean };
      };
    };
  };
}

export interface LoadedModel {
  model_name: string;
  type: 'llm' | 'audio' | 'embedding' | 'reranking' | 'image';
  device: string; // e.g., "cpu", "gpu", "npu", "gpu npu"
  backend?: string;
}

export interface ServerHealth {
  status: string;
  all_models_loaded: LoadedModel[];
  max_models?: {
    llm?: number;
    audio?: number;
    tts?: number;
    embedding?: number;
    reranking?: number;
    image?: number;
  };
}

export interface IPC {
  // Interview operations
  startInterview: (config: Partial<Interview>, personaId?: string) => Promise<Interview>;
  endInterview: (interviewId: string) => Promise<Interview>;
  sendMessage: (interviewId: string, message: string) => Promise<Message>;
  sendMessageStreaming: (interviewId: string, message: string) => Promise<Message>;
  onLLMToken: (callback: (token: string) => void) => void;
  offLLMToken: () => void;
  onLLMDone: (callback: (response: string) => void) => void;
  offLLMDone: () => void;
  onLLMError: (callback: (error: string) => void) => void;
  offLLMError: () => void;
  getInterview: (interviewId: string) => Promise<Interview>;
  getAllInterviews: () => Promise<Interview[]>;
  deleteInterview: (interviewId: string) => Promise<void>;
  updateInterviewTranscript: (interviewId: string, transcript: Message[]) => Promise<void>;
  
  // Job operations
  createJob: (job: Partial<Job>) => Promise<Job>;
  updateJob: (jobId: string, updates: Partial<Job>) => Promise<Job>;
  getJob: (jobId: string) => Promise<Job>;
  getAllJobs: () => Promise<Job[]>;
  deleteJob: (jobId: string) => Promise<void>;
  
  // Settings operations
  getSettings: () => Promise<UserSettings>;
  updateSettings: (settings: Partial<UserSettings>) => Promise<UserSettings>;
  getInterviewerSettings: () => Promise<InterviewerSettings>;
  updateInterviewerSettings: (settings: Partial<InterviewerSettings>) => Promise<InterviewerSettings>;
  
  // Model operations
  getAvailableModels: () => Promise<ModelConfig[]>;
  testModelConnection: (modelId: string) => Promise<boolean>;
  loadModel: (modelId: string, options?: {
    ctx_size?: number;
    llamacpp_backend?: 'vulkan' | 'rocm' | 'metal' | 'cpu';
    llamacpp_args?: string;
    save_options?: boolean;
  }) => Promise<{ success: boolean; message?: string } | false>;
  unloadModel: (modelId: string) => Promise<{ success: boolean; message?: string } | false>;
  pullModel: (modelId: string) => Promise<{ success: boolean; message?: string } | false>;
  pullModelStreaming: (modelId: string) => Promise<{ success: boolean; message?: string } | false>;
  onPullProgress: (callback: (data: {
    file?: string;
    fileIndex?: number;
    totalFiles?: number;
    bytesDownloaded?: number;
    bytesTotal?: number;
    percent: number;
  }) => void) => void;
  offPullProgress: () => void;
  deleteModel: (modelId: string) => Promise<{ success: boolean; message?: string } | false>;
  listAllModels: () => Promise<CompatibleModel[]>;
  
  // Server operations
  checkServerHealth: () => Promise<boolean>;
  getServerStatus: () => Promise<{ isRunning: boolean; url: string }>;
  getWebSocketPort: () => Promise<number | null>;
  refreshModels: () => Promise<ModelConfig[]>;
  getSystemInfo: () => Promise<SystemInfo | null>;
  getServerHealth: () => Promise<ServerHealth | null>;
  checkLemonadeInstallation: () => Promise<{
    installed: boolean;
    version: string | null;
    binaryPath: string | null;
  }>;
  
  // Persona operations
  createPersona: (personaData: Partial<AgentPersona>) => Promise<AgentPersona>;
  getAllPersonas: () => Promise<AgentPersona[]>;
  getPersonaById: (personaId: string) => Promise<AgentPersona>;
  updatePersona: (personaId: string, updates: Partial<AgentPersona>) => Promise<AgentPersona>;
  deletePersona: (personaId: string) => Promise<boolean>;
  setDefaultPersona: (personaId: string) => Promise<boolean>;
  getDefaultPersona: () => Promise<AgentPersona | null>;
  generatePersona: (input: {
    jobDescriptionText: string;
    resumeText: string;
    interviewType: string;
    company: string;
    position: string;
  }) => Promise<{
    persona: AgentPersona;
    jobAnalysis: string;
    resumeAnalysis: string;
  }>;

  // Audio operations
  saveAudioRecording: (audioData: { interviewId: string; messageId: string; audioBlob: string }) => Promise<{ success: boolean; filepath: string }>;
  getAudioRecordingsPath: () => Promise<string>;
  deleteAudioRecording: (filepath: string) => Promise<{ success: boolean; error?: string }>;

  // Feedback operations
  generateFeedback: (interviewId: string) => Promise<InterviewFeedback>;
  onFeedbackProgress: (callback: (data: { questionIndex: number; totalQuestions: number; status: string }) => void) => void;
  offFeedbackProgress: () => void;

  // Document operations
  uploadDocument: (data: { type: 'resume' | 'job_post'; fileName: string; fileData: string }) => Promise<UploadedDocument>;
  getDocuments: (type?: 'resume' | 'job_post') => Promise<UploadedDocument[]>;
  getDocument: (id: string) => Promise<UploadedDocument | null>;
  getDocumentFileData: (id: string) => Promise<{ base64: string; mimeType: string; fileName: string } | null>;
  deleteDocument: (id: string) => Promise<boolean>;
  extractJobDetails: (jobPostDocId: string) => Promise<{
    title: string;
    company: string;
    position: string;
    interviewType: string;
  }>;

  // MCP operations
  getMCPServers: () => Promise<MCPServer[]>;
  updateMCPServers: (servers: MCPServer[]) => Promise<void>;
}

// ============================================================================
// PHASE-AWARE INTERVIEW TYPES
// ============================================================================
// These types support the new phase-specific prompt architecture

/**
 * InterviewPhase enum - defines the 10 sequential phases of an interview
 * Each phase has explicit turn-taking semantics and wait-for-response requirements
 */
export type InterviewPhase =
  | 'phase_0_audio_check'      // Verify audio connection
  | 'phase_1_warm_rapport'     // Build initial connection
  | 'phase_2_session_overview' // Set expectations
  | 'phase_3_q1_warmup'        // Baseline calibration
  | 'phase_4_q2_technical'     // Core technical assessment
  | 'phase_5_q3_behavioral'    // STAR-structured behavioral
  | 'phase_6_q4_validation'    // Resume fact-check
  | 'phase_7_q5_deep_dive'     // Advanced expertise demo
  | 'phase_8_candidate_questions' // Candidate's turn
  | 'phase_9_closing';         // Warm parting

/**
 * Phase numbering for numeric comparisons
 */
export const PHASE_NUMBERS: Record<InterviewPhase, number> = {
  'phase_0_audio_check': 0,
  'phase_1_warm_rapport': 1,
  'phase_2_session_overview': 2,
  'phase_3_q1_warmup': 3,
  'phase_4_q2_technical': 4,
  'phase_5_q3_behavioral': 5,
  'phase_6_q4_validation': 6,
  'phase_7_q5_deep_dive': 7,
  'phase_8_candidate_questions': 8,
  'phase_9_closing': 9,
};

/**
 * Get next phase in sequence
 */
export function getNextPhase(currentPhase: InterviewPhase): InterviewPhase | null {
  const currentNum = PHASE_NUMBERS[currentPhase];
  const nextNum = currentNum + 1;
  const nextPhase = Object.entries(PHASE_NUMBERS).find(([_, num]) => num === nextNum);
  return nextPhase ? nextPhase[0] as InterviewPhase : null;
}

/**
 * Check if phase is a greeting phase (0-2)
 */
export function isGreetingPhase(phase: InterviewPhase): boolean {
  return PHASE_NUMBERS[phase] <= 2;
}

/**
 * Check if phase is an interview question phase (3-7)
 */
export function isInterviewPhase(phase: InterviewPhase): boolean {
  const num = PHASE_NUMBERS[phase];
  return num >= 3 && num <= 7;
}

/**
 * Check if phase is the closing phase (8-9)
 */
export function isClosingPhase(phase: InterviewPhase): boolean {
  return PHASE_NUMBERS[phase] >= 8;
}

/**
 * Phase configuration - defines behavior for a specific interview phase
 */
export interface PhaseConfig {
  phase_number: number;
  phase_name: string;
  description: string;
  system_prompt: string[];
  expected_candidate_response: string;
  response_patterns: {
    confirmation?: string[];
    audio_issues?: string[];
    shallow?: string[];
    strong?: string[];
    vague_technical?: string[];
    depth_indicators?: string[];
    hypothetical?: string[];
    star_complete?: string[];
    team_not_personal?: string[];
    vague_claim?: string[];
    specific_evidence?: string[];
    expertise_depth?: string[];
    time_pressure?: string[];
    has_questions?: string[];
    no_questions?: string[];
    acknowledgment?: string[];
    session_questions?: string[];
    background_response?: string[];
    technical_deep_dive?: string[];
    star_structured_story?: string[];
    specific_claim_evidence?: string[];
    advanced_expertise?: string[];
    questions_about_role?: string[];
    none_final_phase?: never[];
  };
  max_exchanges: number;
  min_exchanges?: number;
  auto_advance: boolean;
  advance_after_exchanges?: number;
  advance_condition?: 'coverage_assessment' | 'star_coverage' | 'validation_complete' | 'expertise_or_time' | 'question_saturation' | 'exchange_based';
  is_final_phase?: boolean;
  variable_injections: string[];
}

/**
 * Transition rule for moving between phases
 */
export interface TransitionRule {
  from: InterviewPhase;
  to: InterviewPhase;
  detection: 'pattern_based' | 'llm_based' | 'exchange_based' | 'exchange_based_or_llm' | 'exchange_based_or_time' | 'exchange_based_or_pattern';
  patterns?: string[];
  patterns_no_questions?: string[];
  any_response?: boolean;
  min_exchanges?: number;
  max_exchanges?: number;
  timeout_seconds?: number;
  on_timeout?: string;
  time_threshold_minutes?: number;
  when_time_low?: string;
  llm_prompt?: string;
}

/**
 * Edge case handler for unexpected situations
 */
export interface EdgeCaseHandler {
  description: string;
  trigger?: string;
  trigger_patterns?: string[];
  strategy: 'prompt_rephrase' | 'acknowledge_and_pivot' | 'brief_answer_then_redirect' | 'force_advance' | 'acknowledge_and_offer_close' | 'one_targeted_followup' | 'deflect_gracefully' | 'rephrase_clearly';
  prompt_addendum?: string;
  recovery_phase?: InterviewPhase;
  max_off_topic_exchanges?: number;
  max_followups_per_phase?: number;
  max_rephrases?: number;
  jump_to_phase?: InterviewPhase;
  escalation?: string;
  actions?: {
    attempt: number;
    prompt_addendum?: string;
    action?: string;
    note?: string;
  }[];
}

/**
 * Time pressure adaptation rules
 */
export interface TimePressureAdaptation {
  trigger_minutes_remaining: number;
  inject_prompt?: string;
  action?: string;
  skip_phases?: InterviewPhase[];
  once_per_session: boolean;
}

/**
 * Persona generation prompt configuration
 */
export interface PersonaGenerationConfig {
  description: string;
  system_prompt: string[];
  user_prompt: string[];
}

/**
 * Feedback prompt configuration
 */
export interface FeedbackConfig {
  description: string;
  comprehensive: {
    system_prompt: string[];
  };
  grading: {
    system_prompt: string[];
    user_prompt: string[];
  };
}

/**
 * Complete phase prompts configuration structure
 */
export interface PhasePromptsConfig {
  _meta: {
    version: string;
    description: string;
    total_phases: number;
    structure: string[];
  };
  core_identity: {
    description: string;
    system_prompt: string[];
    variable_definitions: Record<string, string>;
  };
  phase_prompts: Record<InterviewPhase, PhaseConfig>;
  transition_rules: {
    description: string;
    detection_methods: Record<string, string>;
    rules: Record<string, TransitionRule>;
    time_pressure_adaptations: {
      midpoint_signal?: TimePressureAdaptation;
      wrap_up_early?: TimePressureAdaptation;
    };
  };
  edge_cases: {
    description: string;
    handlers: Record<string, EdgeCaseHandler>;
  };
  phase_recovery: {
    description: string;
    transcript_analysis_rules: {
      pattern: string;
      indicates: string;
      confidence: 'high' | 'medium' | 'low';
    }[];
    llm_rebuild_prompt: string;
  };
  persona_generation?: PersonaGenerationConfig;
  feedback?: FeedbackConfig;
}

/**
 * Interview phase state tracking
 */
export interface InterviewPhaseState {
  currentPhase: InterviewPhase;
  previousPhase: InterviewPhase | null;
  phaseEnterTimeMs: number;
  exchangeCountInPhase: number;
  totalExchangesInInterview: number;
  phaseHistory: {
    phase: InterviewPhase;
    enteredAt: string;
    exchanges: number;
    exitedAt?: string;
  }[];
  // Edge case tracking
  noResponseAttempts: number;
  offTopicExchangeCount: number;
  lastFollowUpSent: boolean;
  // Time tracking
  greetingPhaseStartMs: number;
  greetingCompleted: boolean;
  // Transitions
  lastTransitionReason?: string;
}

/**
 * Initial phase state factory
 */
export function createInitialPhaseState(): InterviewPhaseState {
  const now = Date.now();
  return {
    currentPhase: 'phase_0_audio_check',
    previousPhase: null,
    phaseEnterTimeMs: now,
    exchangeCountInPhase: 0,
    totalExchangesInInterview: 0,
    phaseHistory: [{
      phase: 'phase_0_audio_check',
      enteredAt: new Date(now).toISOString(),
      exchanges: 0,
    }],
    noResponseAttempts: 0,
    offTopicExchangeCount: 0,
    lastFollowUpSent: false,
    greetingPhaseStartMs: now,
    greetingCompleted: false,
  };
}

/**
 * Phase transition result
 */
export interface PhaseTransitionResult {
  shouldTransition: boolean;
  newPhase: InterviewPhase | null;
  reason: string;
  confidence: 'high' | 'medium' | 'low';
  edgeCaseTriggered?: string;
}
